name: "Campfire"
liveurl: https://campfire.waitoru.org
title: "Campfire recipe box"
description: "All the best burnt offerings from the Scouts of Aotearoa"
#disqus: 'demowebsite'
favicon: 'assets/images/logo.webp'
google_analytics: 'UA-16040666-10'
include: ["_pages"]
logo: 'assets/images/logo.webp'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=xxxxxxxxxxxxxxxxxxx&amp;id=xxxxxxxxx'
permalink: /:title/

pwa:
  cacheName: "campfire-v"
  cacheVersion: 2

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    year: '/year/:year/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [ docker-compose.yml, Gemfile, Gemfile.lock, licenses/*,]
