description: "All the best burnt offerings from the Scouts of Aotearoa"
favicon: 'assets/images/logo.webp'
google_analytics: 'G-JYZGLT3LQ9'
include: ["_pages"]
liveurl: https://campfire.waitoru.org
logo: 'assets/images/logo.webp'
name: "Campfire"
permalink: /:title/
title: "Campfire recipe box"
#disqus: 'demowebsite'
#mailchimp-list: 'https://xxxx.us11.list-manage.com/subscribe/post?u=xxxxxxxxxxxxxxxxxxx&amp;id=xxxxxxxxx'

pwa:
  cacheName: "campfire-v"
  cacheVersion: 2

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
#    - categories
#    - tags
    - year
    - month
  layout: archive
  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'
    year: '/year/:year/'
    month: '/month/:year/:month/'
    
#tag_page_layout: tag
#tag_page_dir: tag

# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [ docker-compose.yml, Gemfile, Gemfile.lock, licenses/*, _pages/tag.md]
